# permissions for end users to view wasmapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: wasmapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-spin
    app.kubernetes.io/part-of: kube-spin
    app.kubernetes.io/managed-by: kustomize
  name: wasmapp-viewer-role
rules:
- apiGroups:
  - operator.kube-spin.mrezhi.net
  resources:
  - wasmapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kube-spin.mrezhi.net
  resources:
  - wasmapps/status
  verbs:
  - get
