apiVersion: operator.kube-spin.mrezhi.net/v1alpha1
kind: WasmApp
metadata:
  labels:
    app.kubernetes.io/name: wasmapp
    app.kubernetes.io/instance: wasmapp-sample
    app.kubernetes.io/part-of: kube-spin
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-spin
  name: wasmapp-sample
spec:
  # TODO(user): Add fields here
